{
  "nodeName": "envoy-node",
  "ingressClasses": ["nginx"],
  "clusters": [
    {
      "apiServer": "https://k3d-cluster1-server-0:6443",
      "ca": "cluster1-ca.crt",
      "tokenPath": "cluster1-token"
    }
  ]
}
